NAV140 - fake wheel encoder data
UBC-OpenRobotics/navigation pull request #9
Opened 2023-06-17 19:58 UTC by Nancy-Makar

Created a fake wheel encoder publisher. Publishes to 2 topics  fake_wheel_encoder_data/right and fake_wheel_encoder_data/left, the data published to both topics is the same (maybe that need to be changed?)
The fake data is constant unless the dynamic parameter is set, then the fake data is dynamic based to data read from vel_cmd topic. The dynamic parameter is false by default.

2023-06-18 19:42 UTC, yel-wishahy commented
@Nancy-Makar  added some review comments, lmk if you have any questions

2023-06-24 20:35 UTC, yel-wishahy requested changes

2023-07-13 08:16 UTC, Nancy-Makar commented on navigation/msg/wheel_encoder_data.msg
> +bool spin_direction
given that we have 2 separate publishers for each of the wheels, why do we need that?

2023-07-14 04:51 UTC, yel-wishahy commented on navigation/msg/wheel_encoder_data.msg
> +bool spin_direction
good catch, no we don't!

2023-07-17 03:36 UTC, yel-wishahy approved these changes

2023-07-29 04:03 UTC, merged